import adduser from "./adduser";
export {default as adduser} from "./adduser";
import apk from "./apk";
export {default as apk} from "./apk";
import apt_add_repository from "./apt-add-repository";
export {default as apt_add_repository} from "./apt-add-repository";
import apt_get from "./apt-get";
export {default as apt_get} from "./apt-get";
import apt_key from "./apt-key";
export {default as apt_key} from "./apt-key";
import apt from "./apt";
export {default as apt} from "./apt";
import bash from "./bash";
export {default as bash} from "./bash";
import bundle from "./bundle";
export {default as bundle} from "./bundle";
import cat from "./cat";
export {default as cat} from "./cat";
import cd from "./cd";
export {default as cd} from "./cd";
import chmod from "./chmod";
export {default as chmod} from "./chmod";
import chown from "./chown";
export {default as chown} from "./chown";
import cmake from "./cmake";
export {default as cmake} from "./cmake";
import conda from "./conda";
export {default as conda} from "./conda";
import configure from "./configure";
export {default as configure} from "./configure";
import cp from "./cp";
export {default as cp} from "./cp";
import curl from "./curl";
export {default as curl} from "./curl";
import diff from "./diff";
export {default as diff} from "./diff";
import dnf from "./dnf";
export {default as dnf} from "./dnf";
import docker_php_ext_install from "./docker-php-ext-install";
export {default as docker_php_ext_install} from "./docker-php-ext-install";
import docker from "./docker";
export {default as docker} from "./docker";
import dotnet from "./dotnet";
export {default as dotnet} from "./dotnet";
import dpkg_architecture from "./dpkg-architecture";
export {default as dpkg_architecture} from "./dpkg-architecture";
import dpkg from "./dpkg";
export {default as dpkg} from "./dpkg";
import echo from "./echo";
export {default as echo} from "./echo";
import exit from "./exit";
export {default as exit} from "./exit";
import _export from "./export";
export {default as _export} from "./export";
import find from "./find";
export {default as find} from "./find";
import firefox from "./firefox";
export {default as firefox} from "./firefox";
import gem from "./gem";
export {default as gem} from "./gem";
import git from "./git";
export {default as git} from "./git";
import go from "./go";
export {default as go} from "./go";
import google_chrome from "./google-chrome";
export {default as google_chrome} from "./google-chrome";
import gpg from "./gpg";
export {default as gpg} from "./gpg";
import gradle from "./gradle";
export {default as gradle} from "./gradle";
import grep from "./grep";
export {default as grep} from "./grep";
import groupadd from "./groupadd";
export {default as groupadd} from "./groupadd";
import jq from "./jq";
export {default as jq} from "./jq";
import ldconfig from "./ldconfig";
export {default as ldconfig} from "./ldconfig";
import ln from "./ln";
export {default as ln} from "./ln";
import locale_gen from "./locale-gen";
export {default as locale_gen} from "./locale-gen";
import ls from "./ls";
export {default as ls} from "./ls";
import make from "./make";
export {default as make} from "./make";
import mkdir from "./mkdir";
export {default as mkdir} from "./mkdir";
import mktemp from "./mktemp";
export {default as mktemp} from "./mktemp";
import mv from "./mv";
export {default as mv} from "./mv";
import mvn from "./mvn";
export {default as mvn} from "./mvn";
import node from "./node";
export {default as node} from "./node";
import npm from "./npm";
export {default as npm} from "./npm";
import nproc from "./nproc";
export {default as nproc} from "./nproc";
import pecl from "./pecl";
export {default as pecl} from "./pecl";
import php from "./php";
export {default as php} from "./php";
import pip from "./pip";
export {default as pip} from "./pip";
import printf from "./printf";
export {default as printf} from "./printf";
import pytest from "./pytest";
export {default as pytest} from "./pytest";
import python from "./python";
export {default as python} from "./python";
import rm from "./rm";
export {default as rm} from "./rm";
import rpm from "./rpm";
export {default as rpm} from "./rpm";
import sed from "./sed";
export {default as sed} from "./sed";
import set from "./set";
export {default as set} from "./set";
import sh from "./sh";
export {default as sh} from "./sh";
import sha256sum from "./sha256sum";
export {default as sha256sum} from "./sha256sum";
import sha512sum from "./sha512sum";
export {default as sha512sum} from "./sha512sum";
import sort from "./sort";
export {default as sort} from "./sort";
import sudo from "./sudo";
export {default as sudo} from "./sudo";
import tar from "./tar";
export {default as tar} from "./tar";
import tee from "./tee";
export {default as tee} from "./tee";
import touch from "./touch";
export {default as touch} from "./touch";
import _true from "./true";
export {default as _true} from "./true";
import unzip from "./unzip";
export {default as unzip} from "./unzip";
import useradd from "./useradd";
export {default as useradd} from "./useradd";
import wget from "./wget";
export {default as wget} from "./wget";
import which from "./which";
export {default as which} from "./which";
import xargs from "./xargs";
export {default as xargs} from "./xargs";
import yarn from "./yarn";
export {default as yarn} from "./yarn";
import yum from "./yum";
export {default as yum} from "./yum";
export const enrichers = [
adduser,apk,apt_add_repository,apt_get,apt_key,apt,bash,bundle,cat,cd,chmod,chown,cmake,conda,configure,cp,curl,diff,dnf,docker_php_ext_install,docker,dotnet,dpkg_architecture,dpkg,echo,exit,_export,find,firefox,gem,git,go,google_chrome,gpg,gradle,grep,groupadd,jq,ldconfig,ln,locale_gen,ls,make,mkdir,mktemp,mv,mvn,node,npm,nproc,pecl,php,pip,printf,pytest,python,rm,rpm,sed,set,sh,sha256sum,sha512sum,sort,sudo,tar,tee,touch,_true,unzip,useradd,wget,which,xargs,yarn,yum,]
